### PR TITLE
Fixing plurals and mistranslation

### PR DESCRIPTION
**Pull request by rcapp**
Small update after skirmishing the file: "Orignal" is singular and "Changes" can be "Mudanças" or "Muda [para]". This should be moved to the Array on the messages.php file.

### CODE REVIEW

**Comment by kitbs** [comment]
Hi @rcapp 

Thank you for contributing, but I don't think I will accept your changes.

I don't really understand your comment about the "Array on the messages.php file". There is no such file in Nova or in this package.

These two strings are used by the action log in Nova to indicate the original and changed values of fields in an Update event. So it would make sense that the translation was plural, i.e. "[Valores] Originais" and "[Valores] Alterados".

**Comment by rcapp** [comment]
Hi, @kitbs! 

You are welcome! 

According to the Laravel documentation regarding translations, we can either use a JSON or an [Array of keyed strings](https://laravel.com/docs/7.x/localization#using-short-keys): 

> All language files return an array of keyed strings. For example:
> 
> ```php 
> <?php
> 
> // resources/lang/en/messages.php
> 
> return [
>     'welcome' => 'Welcome to our application'
> ];
> ``` 
>

Because some languages may have the same English word meaning different things depending on the contexts, may not be gender neutral for its prepositions and so on, having them in the JSON word list may lead to wrong translation or confusion. For instance, `Changes` can mean `more than one modification` (mais de uma **mudança**) or `it changes to something else` (**muda** para outra coisa)

Nonetheless, thank you for your feedback.

Cheers!

**Comment by kitbs** [comment]
Hi @rcapp 

I really do agree that there are problems with using a single JSON list. I think it's very English-centric and doesn't take into account the problems that you have described. There are also problems with strings like `"New :resource"`, because if we don't know the gender of the resource, it could be e.g. "Nov**o** arquivo" or "Nov**a** página".

But unfortunately our repository is just for translations of the files provided by the Nova platform, so any issues with the way the files are structured or the difficulties in translating them would have to be taken up with the Nova team (https://github.com/laravel/nova-issues). We are community-run and not affiliated with the Nova project.

Thanks again for taking the time to comment.

**Comment by rcapp** [comment]
I understand. Thank you for your feedback!

Have a good one!

**Pull request closed without merging**
