### PR TITLE
Update fr.json

### PR DESCRIPTION
**Pull request by KillianH**
Fixed mistake on the "Per Page" translation
Updated Translation for "The :resource was updated!" translation

### CODE REVIEW

**Comment by hivokas** [comment]
Should it be `Par page :` with ` :` as a value?

**Comment by KillianH** [comment]
I don't think so. There's no value in the original translation : "Per Page": "Per Page",

**Comment by hivokas** [comment]
Then fix it please.

**Comment by KillianH** [comment]
There's nothing to fix.
The original translation : 
`"Per Page:": "Par page :",`
But the key is wrong so I've just fixed the key. The `:` in the translation is meant to be displayed.

**Comment by hivokas** [comment]
I think it should not be displayed in the translation.
Because `en.json` contains `"Per Page": "Per Page",` without `:`

**Comment by KillianH** [comment]
Done. :)

**Comment by hivokas** [comment]
Thanks

**Pull request merged**
