### PR TITLE
1.1 uz lang

### PR DESCRIPTION
**Pull request by shokhaa**
uz latin 100% successfully done!

### CODE REVIEW

**Comment by hivokas** [comment]
Thanks for the contribution!
Let's rename the language files to `uz‑Latn`.

**Comment by shokhaa** [comment]
ur welcome!

**Comment by hivokas** [comment]
And let's use ' instead of `.

**Comment by shokhaa** [comment]
success

**Comment by hivokas** [comment]
Let's use ' instead of `.

**Comment by kitbs** [comment]
Rahmat, @shokhaa!

**Pull request merged**
