### PR TITLE
Implemented aliases

### PR DESCRIPTION
**Pull request by kitbs**
Implemented aliases as per idea #168.

### CODE REVIEW

**Comment by hivokas** [comment]
I think that zhHans and other language specific flags are excess.

**Comment by hivokas** [comment]
Are such cases really common?

**Comment by kitbs** [comment]
Yeah, I see your point.

My reasoning was that big standardisation projects like IANA and CLDR have recommended to use Brazilian Portuguese and Cyrillic Serbian as the default, and Chinese with scripts instead of country. So the way they're coded in our repo is non-standard, but it would be a breaking change to rename our files.

Perhaps I could just provide suggestions in the README for what aliases to use if the user is interested in these cases?

**Comment by kitbs** [comment]
Yeah, I see your point.

My reasoning was that big standardisation projects like IANA and CLDR have recommended to use Brazilian Portuguese and Cyrillic Serbian as the default, and Chinese with scripts instead of country. So the way they're coded in our repo is non-standard, but it would be a breaking change to rename our files.

Perhaps I could just provide suggestions in the README for what aliases to use if the user is interested in these cases?

**Comment by hivokas** [comment]
I think that suggestions in readme would be enough.
Because honestly I don't think that developers who use this package will assume that such flags even exist.

**Comment by kitbs** [comment]
Removed predefined aliases and included examples in the readme. Also ensured the separator was standardised when publishing. Closes #168 and closes part of #167.

**Comment by hivokas** [comment]
Good job! 💪

**Pull request merged**
