### PR TITLE
Fix double-escaped apostrophes

### PR DESCRIPTION
**Pull request by kitbs**
JSON keys containing `'` had been escaped to `\'` and then double-escaped to `\\'` so were not being recognised as valid keys. Cote D'Ivoire had become `Cote D\\ \\ 'Ivoire` in **es** and **ca**.

### CODE REVIEW

**Comment by hivokas** [comment]
Thanks for the contribution!!

**Comment by hivokas** [comment]
Unfortunately, I can't merge this PR because of a conflict.

**Comment by kitbs** [comment]
I have fixed the conflict in the nl.json file.

**Comment by hivokas** [comment]
Merged, thanks.

**Pull request merged**
